language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.6'
  - os: linux
    dist: trusty
    python: '2.7'
  - os: linux
    dist: trusty
    python: '3.3'
  - os: linux
    dist: trusty
    python: '3.4'
  - os: linux
    dist: trusty
    python: '3.5'
  - os: linux
    dist: trusty
    python: '3.6'
  - os: linux
    dist: trusty
    python: pypy
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.2
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  provider: pypi
  user: robermorales
  password:
    secure: LbjZQCcVX5ZdAtlfwm69Wwbl30n2PMWrlGI/DVivJzH0+bKtMc0V4hznrcFp+k/BD7S7UL0KH8mWO1vWGB0YLPqo6jyjfkCvVN7Qi4LOd2xRYZQB3zGfgUz5f9ZPy3IhGZkWR0Zw2s5npZyTo/j6TKJoXXOGE8jEZBgNx36/vTIkgcAeyhd5hB1Va6RcbVNrXozgWS4iPCYeCOW1zTZubzbvxlZQfWwP/qYbPILZFAAEO0F1FuonLXVxr/CbgxDmwD+nxlic16nbRHcNdVnOtAQKDXlNjxqeQpyukUQ+aOmlDNfHt60+gDUPin8XibrL+ytf31DcbZl3GS9hVQDKqr6ONm8+w7cqHTzG9MZkYJ3HwrkzFmJ1CzSZfOQDcRazVWK6X6j/wPuFWgjjPvxonmtYmASeOfR8RTiWzjTXDmRSHkISlxlpCdtcfynwF8mjrlR9p74jCR57d33gtDHdEx1uPmXRbnrhT/EplJ5ujoqJKOHQFaCD5SJMqp4wo8CmjsdVPB4GvhCJaNMXgLFOMtUjaGrj9tiFDtGxNINL9BuAs5H7clRjOTTh0eCPBYPeURsb3ocRJfi6RrtLOoZJ2eOxc1C+ViiEoO2L3cTtua0UCFotwXzhpouJrE5hDJIuaJ181F09O7QdpGlk6u3mLytiuvpO31AxybhwlyZ+yWM=
  on:
    distributions: bdist_wheel
    repo: rstorcloud/validjson
