language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.6'
  - os: linux
    dist: trusty
    python: '2.7'
  - os: linux
    dist: trusty
    python: '3.3'
  - os: linux
    dist: trusty
    python: '3.4'
  - os: linux
    dist: trusty
    python: '3.5'
  - os: linux
    dist: trusty
    python: '3.6'
  - os: linux
    dist: trusty
    python: pypy
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.2
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  provider: pypi
  user: robermorales
  password:
    secure: dbtOSBCNCN9yt2ksXS4a2bhicdH/qBQI5NeTZQDaRHbWCrEkFhAkaFuCl8qbV42l+/nX+47NwDZjnv2XCnlVeRsMqhMzQUIIffKgKBkWyvlVX1aUiWhiN32pfbU0COmQ/MTf2LberCD6pFsio4FOGhfPn7EdP/xlhBGjx7GMdqKh9suvnVDqP40jPMsme90QqYaFbsCPQCI1kb9mCbnOvoX9JSVMw0D5xSzVDFqaWER8jYgoGjpfqimwz1qtfbEQK8CRltqh2LI4DcASqDG1n9t2Olc7KShghdPkTvWVeoiZLUZ0MIDRTNMGPxcOPc9yYbMdFq/kN0415p0LrCIdOQqD36DRsvD8MPjjIE2Y1NWg3W3izgyJWXEx09AopEqjtxgs9Eujg0FdUkDBqZsEo4cY0vIQwTPVvnzC6KMlN+v11tGYbt9Ve3YQh/V+QbmoTBIZ5Ile0AYfrQqWqLGSE6DfB6wj8ZwKT6i/Bu7XehHszX/hvDFvyEXn5j1LAUfBWPH+IB9Kx5gYDSmS0CuXFtr80CoOt6gp4F/u4Dw/pPDxeMcpqAhvkGTQDlTHJYMS7VUUhnbo2485G1S6SJbxJSGfnzF/MDQcMSe3h3u4byJ+llWoEsOP5X4zQB2cA/w7NfXa97eLygj8OeePq7RbVqCzZh8SEP6vmcRg67xHuUA=
  on:
    distributions: sdist bdist_wheel
    repo: rstorcloud/validjson
